---


- name: Create hellok8s deployment from an inline definition
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hello-k8s
        namespace: default
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: hello-k8s
        template:
          metadata:
            labels:
              app: hello-k8s
          spec:
            containers:
            - name: hello-k8s
              image: paulbouwer/hello-kubernetes:1.5
              ports:
              - containerPort: 8080

- name: Create a Service object from an inline definition
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: hello-k8s
        namespace: default
      spec:
        type: NodePort
        ports:
        - port: 8080
          targetPort: 8080
        selector:
          app: hello-k8s


- name: Get hello-k8s service details
  k8s_info:
    kind: Service
    name: hello-k8s
    namespace: default
  register: svc

- name: Print the full svc variable
  debug: var=svc

- name: Set the service NodePort as a variable
  set_fact:
    port: "{{ svc['resources'][0]['spec']['ports'][0]['nodePort'] }}"


- name: Test a request to the service
  uri:
    url: http://{{ master_ip }}:{{ port }}/

- name: Print the URL for hello-k8s
  debug:
    msg: http://{{ master_ip }}:{{ port }}/

