---

#https://betterprogramming.pub/monitor-your-kubernetes-cluster-with-prometheus-and-grafana-1f7d0195e59

#- name: Add stable repo for Helm
#  command: "helm repo add stable https://charts.helm.sh/stable"


#https://docs.ansible.com/ansible/latest/collections/community/kubernetes/helm_module.html
# From repository
- name: Add stable chart repo
  community.kubernetes.helm_repository:
    name: stable
    repo_url: "https://charts.helm.sh/stable"

- name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
  community.kubernetes.helm:
    name: "prometheus"
    chart_ref: "stable/prometheus-operator"
    release_namespace: "monitoring"
    create_namespace: "true"
    values_files:
      - /mnt/nfs/values_prometheus_mariadb.yaml

      #- name: Install Prometheus with Helm
      #  command: "helm install prometheus stable/prometheus-operator --namespace monitoring --values /mnt/nfs/values_prometheus_mariadb.yaml"


- name: Expose https port with ClusterIP
  community.kubernetes.k8s_service:
    state: present
    name: test-https
    namespace: default
    ports:
    - port: 443
      protocol: TCP
    selector:
      key: special

- name: Prometheus Service
  k8s_service:
    state: present
    apply: yes
    name: prometheus-prometheus-oper-prometheus
    namespace: monitoring
    type: NodePort
    ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30909

- name: Grafana Service
  k8s_service:
    state: present
    apply: yes
    name: prometheus-grafana
    namespace: monitoring
    type: NodePort
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30910


# vim: ff=unix:ai:et:sw=2:ts=2:
