---

# tasks file for ansible-k8s-deploy
#

#- name: PV and PVC NFS template upload
#  template:
#    src: "nfs-pv-pvc.yaml.j2"
#    dest: "/home/{{ provision_cluster_user }}"
#    owner: "{{ provision_cluster_user }}"
#    group: wheel
#    mode: '0644'


- name: Docker configuration
  include_tasks: docker_conf.yml


#https://github.com/kubernetes/kubernetes/issues/71305
#https://docs.oracle.com/en/operating-systems/oracle-linux/kubernetes/kube_admin_config.html#kube_admin_config_iptables
- name: Aceptar Forwarding
  iptables:
    chain: FORWARD
    jump: ACCEPT


#- name: Deploy hello-go
#  include_tasks: deploy_hello_go.yml

#- name: Deploy hello-k8s
#  include_tasks: deploy_hello_k8s.yml

- name: Deploy tomcat
  include_tasks: deploy_tomcat.yml

- name: Deploy MySQL
  include_tasks: deploy_mysql.yml

