---

- name: Docker configuration
  include_tasks: docker_conf.yml


#https://github.com/kubernetes/kubernetes/issues/71305
#https://docs.oracle.com/en/operating-systems/oracle-linux/kubernetes/kube_admin_config.html#kube_admin_config_iptables
- name: Aceptar Forwarding
  iptables:
    chain: FORWARD
    jump: ACCEPT


#- name: Deploy hello-go
#  include_tasks: deploy_hello_go.yml

#- name: Deploy hello-k8s
#  include_tasks: deploy_hello_k8s.yml

- name: Deploy tomcat
  include_tasks: deploy_tomcat.yml

- name: Deploy MySQL
  include_tasks: deploy_mysql.yml

- name: Deploy Mattermost
  include_tasks: deploy_mattermost.yml

- name: Create secrets
  include_tasks: setup_secrets.yml

- name: Setup nginx ingress
  include_tasks: setup_nginx_ingress.yml


# vim: ff=unix:ai:et:sw=2:ts=2:
