---

#### Dashboard TLS conf (when kubernetes_enable_web_ui = true)

- name: Check if tls secret "tls-dashb-certificate" already exists
  shell: kubectl get secrets -nkubernetes-dashboard | grep tls-dashb-certificate
  delegate_to: master
  run_once: true
  register: check_tls_dashb_secret
  ignore_errors: true

- name: Generate SSL key and certificate
  shell: |
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout {{ deployment_dir }}/ssl/certs/nginx-selfsigned-dashb.key \
      -out {{ deployment_dir }}/ssl/certs/nginx-selfsigned-dashb.crt \
      -subj "/CN=dashboard.k8s.ingress.{{ fqdn }}"
  when: check_tls_dashb_secret is failed

- name: Create tls secret dashb
  shell: kubectl create secret tls tls-dashb-certificate --key {{ deployment_dir }}/ssl/certs/nginx-selfsigned-dashb.key --cert {{ deployment_dir }}/ssl/certs/nginx-selfsigned-dashb.crt -nkubernetes-dashboard
  when: check_tls_dashb_secret is failed

- name: Check if "tls-dashb-dhparam" secret already exists
  shell: kubectl get secrets -nkubernetes-dashboard | grep tls-dashb-dhparam
  delegate_to: master
  run_once: true
  register: check_dhparam_dashb_secret
  ignore_errors: true

- name: Generate X bit dhparam.pem file (this may take a while)
  shell: openssl dhparam -out {{ deployment_dir }}/ssl/certs/dhparam_dashb.pem 2048
  when: check_tls_dashb_secret is failed

# Fixme
- name: Create tls-dhparam secret
  shell: kubectl create secret generic tls-dashb-dhparam --from-file="{{ deployment_dir }}/ssl/certs/dhparam_dashb.pem" -nkubernetes-dashboard
  when: check_dhparam_dashb_secret is failed

# vim: ff=unix:ai:et:sw=2:ts=2:
